# Generated by Django 2.2.1 on 2019-05-09 03:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('articleId', models.CharField(max_length=36, primary_key=True, serialize=False, verbose_name='文章ID')),
                ('title', models.CharField(max_length=255, verbose_name='文章标题')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发表时间')),
                ('illustration', models.CharField(max_length=255, verbose_name='文章封面')),
                ('status', models.CharField(default='01', max_length=4, verbose_name='文章状态（00-已发布  01-编辑中  02-审核中  99-已删除）')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modifyTime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tagId', models.AutoField(primary_key=True, serialize=False, verbose_name='标签ID')),
                ('tagName', models.CharField(max_length=10, verbose_name='标签名')),
                ('status', models.CharField(default='00', max_length=4, verbose_name='标签状态（00-有效  99-已删除）')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('typeId', models.AutoField(primary_key=True, serialize=False)),
                ('typeName', models.CharField(max_length=32, verbose_name='类型名称')),
                ('status', models.CharField(default='00', max_length=4, verbose_name='类型状态')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='用户ID')),
                ('openId', models.CharField(max_length=32, verbose_name='微信小程序身份唯一标识')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('head', models.CharField(max_length=32, verbose_name='用户头像')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('status', models.CharField(default='00', max_length=4, verbose_name='账号状态（00-有效  01-注销）')),
                ('lastLoginTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后登录时间')),
            ],
        ),
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('remarkId', models.CharField(max_length=36, primary_key=True, serialize=False, verbose_name='评论ID')),
                ('content', models.TextField(max_length=255, verbose_name='评论内容')),
                ('status', models.CharField(default='01', max_length=4, verbose_name='评论状态（00-有效  01-待审核  99-已删除）')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('articleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_model.Article', verbose_name='文章ID')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_model.User', verbose_name='用户ID')),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('bannerId', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='轮播图显示的标题')),
                ('resurl', models.CharField(max_length=2048, verbose_name='资源路径')),
                ('type', models.CharField(max_length=2, verbose_name='显示类型（0-图片 1-视频）')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('articleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_model.Article', verbose_name='文章ID')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='articleTags',
            field=models.ManyToManyField(to='db_model.Tag'),
        ),
        migrations.AddField(
            model_name='article',
            name='articleType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_model.Type', verbose_name='文章类型'),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_model.User', verbose_name='作者'),
        ),
        migrations.CreateModel(
            name='LikeRel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=4, verbose_name='状态（00-有效  01-失效）')),
                ('articleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_model.Article', verbose_name='文章ID')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_model.User', verbose_name='用户ID')),
            ],
            options={
                'unique_together': {('userId', 'articleId')},
            },
        ),
    ]
