# Generated by Django 2.2.1 on 2019-05-06 03:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('articleId', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('articleType', models.IntegerField()),
                ('articleTags', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.CharField(max_length=64)),
                ('illustration', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=4)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('modifyTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('bannerId', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('articleId', models.CharField(max_length=36)),
                ('resurl', models.CharField(max_length=2048)),
                ('type', models.CharField(max_length=2)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('remarkId', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('articleId', models.CharField(max_length=36)),
                ('userId', models.CharField(max_length=15)),
                ('content', models.TextField(max_length=255)),
                ('status', models.CharField(max_length=4)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tagId', models.IntegerField(primary_key=True, serialize=False)),
                ('tagName', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=4)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('typeId', models.IntegerField(primary_key=True, serialize=False)),
                ('typeName', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=4)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('openId', models.CharField(max_length=32)),
                ('username', models.CharField(max_length=32)),
                ('head', models.CharField(max_length=32)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=4)),
                ('lastLoginTime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LikeRel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=4)),
                ('articleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_model.Article')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_model.User')),
            ],
            options={
                'unique_together': {('userId', 'articleId')},
            },
        ),
    ]
