# Generated by Django 2.2.1 on 2019-05-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='illustration',
            field=models.ImageField(blank=True, null=True, upload_to='images/illustrations/%Y/%m/%d', verbose_name='文章封面'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='resurl',
            field=models.FileField(blank=True, null=True, upload_to='images/files/%Y/%m/%d', verbose_name='资源路径'),
        ),
        migrations.AlterField(
            model_name='type',
            name='status',
            field=models.CharField(default='00', max_length=4, verbose_name='类型状态（00-有效  99-已删除）'),
        ),
        migrations.AlterField(
            model_name='user',
            name='head',
            field=models.ImageField(blank=True, null=True, upload_to='images/heads/%Y/%m/%d', verbose_name='用户头像'),
        ),
    ]
