# Generated by Django 2.2.1 on 2019-05-06 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='articleType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_model.Type'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_model.User'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='articleId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_model.Article'),
        ),
        migrations.AlterField(
            model_name='remark',
            name='articleId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_model.Article'),
        ),
        migrations.AlterField(
            model_name='remark',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_model.User'),
        ),
    ]
