# Generated by Django 2.2.1 on 2019-05-06 08:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('db_model', '0002_auto_20190506_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='articleId',
            field=models.CharField(max_length=36, primary_key=True, serialize=False, verbose_name='文章ID'),
        ),
        migrations.AlterField(
            model_name='article',
            name='articleTags',
            field=models.CharField(max_length=20, verbose_name='文章标签'),
        ),
        migrations.AlterField(
            model_name='article',
            name='articleType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_model.Type', verbose_name='文章类型'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_model.User', verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='文章内容'),
        ),
        migrations.AlterField(
            model_name='article',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='发表时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='illustration',
            field=models.CharField(max_length=255, verbose_name='文章封面'),
        ),
        migrations.AlterField(
            model_name='article',
            name='modifyTime',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(default='01', max_length=4, verbose_name='文章状态：00-已发布  01-编辑中  02-审核中  99-已删除'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255, verbose_name='文章标题'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='articleId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_model.Article', verbose_name='文章ID'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='resurl',
            field=models.CharField(max_length=2048, verbose_name='资源路径'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=255, verbose_name='轮播图显示的标题'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='type',
            field=models.CharField(max_length=2, verbose_name='显示类型: 0-图片 1-视频'),
        ),
        migrations.AlterField(
            model_name='likerel',
            name='articleId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_model.Article', verbose_name='文章ID'),
        ),
        migrations.AlterField(
            model_name='likerel',
            name='status',
            field=models.CharField(max_length=4, verbose_name='状态：00-有效  01-失效'),
        ),
        migrations.AlterField(
            model_name='likerel',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_model.User', verbose_name='用户ID'),
        ),
        migrations.AlterField(
            model_name='remark',
            name='articleId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_model.Article', verbose_name='文章ID'),
        ),
        migrations.AlterField(
            model_name='remark',
            name='content',
            field=models.TextField(max_length=255, verbose_name='评论内容'),
        ),
        migrations.AlterField(
            model_name='remark',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='remark',
            name='remarkId',
            field=models.CharField(max_length=36, primary_key=True, serialize=False, verbose_name='评论ID'),
        ),
        migrations.AlterField(
            model_name='remark',
            name='status',
            field=models.CharField(default='01', max_length=4, verbose_name='评论状态：00-有效  01-待审核  99-已删除'),
        ),
        migrations.AlterField(
            model_name='remark',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_model.User', verbose_name='用户ID'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='status',
            field=models.CharField(default='00', max_length=4, verbose_name='标签状态：00-有效  99-已删除'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tagId',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='标签ID'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tagName',
            field=models.CharField(max_length=10, verbose_name='标签名'),
        ),
        migrations.AlterField(
            model_name='type',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='type',
            name='status',
            field=models.CharField(default='00', max_length=4, verbose_name='类型状态'),
        ),
        migrations.AlterField(
            model_name='type',
            name='typeName',
            field=models.CharField(max_length=32, verbose_name='类型名称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='注册时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='head',
            field=models.CharField(max_length=32, verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastLoginTime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后登录时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='openId',
            field=models.CharField(max_length=32, verbose_name='微信小程序身份唯一标识'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(default='00', max_length=4, verbose_name='账号状态：00-有效  01-注销'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userId',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='用户ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=32, verbose_name='用户名'),
        ),
    ]
