# Generated by Django 2.2.1 on 2019-05-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_model', '0003_auto_20190506_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remark',
            name='status',
            field=models.CharField(default='01', max_length=4, verbose_name='评论状态\n(00-有效  01-待审核  99-已删除)'),
        ),
    ]
