# Generated by Django 2.2.1 on 2019-05-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_model', '0004_auto_20190509_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='bannerId',
            field=models.CharField(max_length=24, primary_key=True, serialize=False),
        ),
    ]
