# Generated by Django 2.2.1 on 2019-05-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_model', '0004_auto_20190506_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(default='01', max_length=4, verbose_name='文章状态(00-已发布  01-编辑中  02-审核中  99-已删除)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='type',
            field=models.CharField(max_length=2, verbose_name='显示类型(0-图片 1-视频)'),
        ),
        migrations.AlterField(
            model_name='likerel',
            name='status',
            field=models.CharField(max_length=4, verbose_name='状态(00-有效  01-失效)'),
        ),
        migrations.AlterField(
            model_name='remark',
            name='status',
            field=models.CharField(default='01', max_length=4, verbose_name='评论状态(00-有效  01-待审核  99-已删除)'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='status',
            field=models.CharField(default='00', max_length=4, verbose_name='标签状态(00-有效  99-已删除)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(default='00', max_length=4, verbose_name='账号状态(00-有效  01-注销)'),
        ),
    ]
