# Generated by Django 2.2.1 on 2019-05-09 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_model', '0005_auto_20190509_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='articleId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db_model.Article', verbose_name='文章ID'),
        ),
    ]
