# Generated by Django 2.2.1 on 2019-05-10 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_model', '0007_auto_20190509_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date'], 'verbose_name': '文章表', 'verbose_name_plural': '文章表'},
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['-createTime'], 'verbose_name': '轮播图表', 'verbose_name_plural': '轮播图表'},
        ),
        migrations.AlterModelOptions(
            name='likerel',
            options={'verbose_name': '点赞关系表', 'verbose_name_plural': '点赞关系表'},
        ),
        migrations.AlterModelOptions(
            name='remark',
            options={'ordering': ['-createTime'], 'verbose_name': '评论表', 'verbose_name_plural': '评论表'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-createTime'], 'verbose_name': '文章标签表', 'verbose_name_plural': '文章标签表'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ['-createTime'], 'verbose_name': '文章类型表', 'verbose_name_plural': '文章类型表'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-createTime'], 'verbose_name': '用户表', 'verbose_name_plural': '用户表'},
        ),
        migrations.AlterField(
            model_name='banner',
            name='resurl',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d', verbose_name='资源路径'),
        ),
    ]
