# Generated by Django 2.2.1 on 2019-05-10 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_model', '0008_auto_20190510_0933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likerel',
            options={'verbose_name': '点赞与收藏关系表', 'verbose_name_plural': '点赞与收藏关系表'},
        ),
        migrations.AddField(
            model_name='likerel',
            name='createTime',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='likerel',
            name='type',
            field=models.CharField(default=0, max_length=4, verbose_name='类型（0-点赞  1-收藏）'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='articleTags',
            field=models.ManyToManyField(blank=True, null=True, to='db_model.Tag'),
        ),
        migrations.AlterField(
            model_name='remark',
            name='articleId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_model.Article', verbose_name='文章'),
        ),
        migrations.AlterField(
            model_name='remark',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_model.User', verbose_name='用户'),
        ),
        migrations.AlterUniqueTogether(
            name='likerel',
            unique_together={('userId', 'articleId', 'type')},
        ),
    ]
