# Generated by Django 2.2.1 on 2019-05-10 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_model', '0009_auto_20190510_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likerel',
            name='type',
            field=models.CharField(default='0', max_length=4, verbose_name='类型（0-点赞  1-收藏）'),
        ),
    ]
