# Generated by Django 2.2.1 on 2019-05-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_model', '0010_auto_20190510_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='发表时间'),
        ),
        migrations.AlterField(
            model_name='likerel',
            name='status',
            field=models.CharField(max_length=4, verbose_name='状态（00-有效  99-取消）'),
        ),
    ]
