# Generated by Django 2.2.1 on 2019-05-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_model', '0012_auto_20190510_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('00', '已发布'), ('01', '编辑中'), ('02', '审核中'), ('99', '已删除')], default='01', max_length=4, verbose_name='文章状态'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='type',
            field=models.CharField(choices=[('0', '图片'), ('1', '视频')], default='0', max_length=2, verbose_name='资源类型'),
        ),
        migrations.AlterField(
            model_name='likerel',
            name='status',
            field=models.CharField(choices=[('00', '有效'), ('99', '已删除')], default='00', max_length=4, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='likerel',
            name='type',
            field=models.CharField(choices=[('0', '点赞'), ('1', '收藏')], default='0', max_length=4, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='remark',
            name='status',
            field=models.CharField(choices=[('00', '有效'), ('01', '待审核'), ('99', '已删除')], default='01', max_length=4, verbose_name='评论状态'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='status',
            field=models.CharField(choices=[('00', '有效'), ('99', '已删除')], default='00', max_length=4, verbose_name='标签状态'),
        ),
        migrations.AlterField(
            model_name='type',
            name='status',
            field=models.CharField(choices=[('00', '有效'), ('99', '已删除')], default='00', max_length=4, verbose_name='类型状态'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('00', '有效'), ('99', '已删除')], default='00', max_length=4, verbose_name='账号状态'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userId',
            field=models.CharField(default='100117519096998', max_length=15, primary_key=True, serialize=False, verbose_name='用户ID'),
        ),
    ]
