# Generated by Django 2.2.1 on 2019-05-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_model', '0013_auto_20190510_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userId',
            field=models.CharField(default='10019011363700', max_length=15, primary_key=True, serialize=False, verbose_name='用户ID'),
        ),
    ]
