# Generated by Django 2.2.1 on 2019-05-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_model', '0014_auto_20190510_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.AlterField(
            model_name='user',
            name='userId',
            field=models.CharField(default='10013518234962', max_length=15, primary_key=True, serialize=False, verbose_name='用户ID'),
        ),
    ]
